#!/usr/bin/bash

i=0
while [ $i -eq 0 ]
do
  read -t 5 
  nivel=$(acpi | cut -d ' ' -f 4 | cut -d ',' -f1 | cut -d '%' -f1)
  estado1=$(cat estado)
  echo $nivel $estado1
  if [ $nivel -gt '10' ] && [ $nivel -lt '95' ]
  then
    if [ $estado1 != 'conectar' ]
    then
      echo 'ok' > estado
    fi
  elif [ $nivel -ge '95' ]
  then
    echo 'desconectar' > estado
  elif [ $nivel -le '10' ]
  then
    echo 'conectar' > estado
  fi

  estado2=$(cat estado)

  if [ $estado1 != $estado2 ]
  then
    git add -A
    git commit -m "$estado2"
    git push
  fi
done

